In [1]:
import numpy as np
np1 = np.array([1,2,3,4,5])
np1

array([1, 2, 3, 4, 5])

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [5]:
arr = np.array([1,2,3,4,5])
np.short(arr)

array([1, 2, 3, 4, 5], dtype=int16)

In [6]:
arr1=np.array([[1,2,3,4],[9,8,7,6]])
arr2=np.array([[3,4,5,6]])
np.concatenate((arr1,arr2), axis=0)

array([[1, 2, 3, 4],
       [9, 8, 7, 6],
       [3, 4, 5, 6]])

In [7]:
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2 = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
arr3 = np.array([[19, 20, 21], [22, 23, 24], [25, 26, 27]])
result = np.concatenate((arr1, arr2, arr3), axis=0)

print(result)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]]


In [8]:
threed = np.array([[[1,2,3],[2,3,4],[4,5,6]],[[1,2,3],[2,3,4],[7,8,9]]])
np.concatenate(threed)

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6],
       [1, 2, 3],
       [2, 3, 4],
       [7, 8, 9]])

In [9]:
threed = np.array([[[1,2,3],[2,3,4],[4,5,6]],[[1,2,3],[2,3,4],[7,8,9]]])
result = np.concatenate(threed)

print(result)


[[1 2 3]
 [2 3 4]
 [4 5 6]
 [1 2 3]
 [2 3 4]
 [7 8 9]]


In [10]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
a

array([[0.45053314, 0.17296777, 0.34376245, 0.5510652 ],
       [0.54627315, 0.05093587, 0.40067661, 0.55645993],
       [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [11]:
arr1= np.array([1,2,3,4]) 
np.save('arr_data.npy', arr1)

In [12]:
arr7=np.load('arr_data.npy')

In [13]:
arr7

array([1, 2, 3, 4])

In [14]:
pip install pandas

  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/77/62/8e11962934e024a093758992bc82711e3e30efd5ea355cbfdc6e1ab5de76/pandas-2.2.0-cp311-cp311-win_amd64.whl.metadata
  Using cached pandas-2.2.0-cp311-cp311-win_amd64.whl.metadata (19 kB)
  Obtaining dependency information for tzdata>=2022.7 from https://files.pythonhosted.org/packages/65/58/f9c9e6be752e9fcb8b6a0ee9fb87e6e7a1f6bcab2cdc73f02bb7ba91ada0/tzdata-2024.1-py2.py3-none-any.whl.metadata
  Using cached tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
Using cached pandas-2.2.0-cp311-cp311-win_amd64.whl (11.6 MB)
Using cached tzdata-2024.1-py2.py3-none-any.whl (345 kB)
Note: you may need to restart the kernel to use updated packages.


In [16]:
arr10 =np.array([[1,2,3,4],[4,5,6,7]])

In [1]:
df=pd.DataFrame(arr10)

NameError: name 'pd' is not defined

In [19]:
df.to_cov('ap.csv')

AttributeError: 'DataFrame' object has no attribute 'to_cov'

In [3]:
pd.read_csv('ap.csv')

NameError: name 'pd' is not defined

In [4]:
pip install pandas


Note: you may need to restart the kernel to use updated packages.


In [5]:
import pandas as pd

C:\Users\QCS\AppData\Local\Temp\ipykernel_7420\4080736814.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [6]:
arr10 =np.array([[1,2,3,4],[4,5,6,7]])

NameError: name 'np' is not defined

In [7]:
import numpy as np

In [8]:
arr10 =np.array([[1,2,3,4],[4,5,6,7]])

In [11]:
df=pd.DataFrame(arr10)

In [12]:
df.to_cov('ap.csv')

AttributeError: 'DataFrame' object has no attribute 'to_cov'